language: node_js
cache:
  directories:
    - ~/.npm
notifications:
  email: false
node_js:
  - '10'
  - '9'
  - '8'
after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ] && [ "${TRAVIS_PULL_REQUEST}" == "false" ]; then
    npm run travis-deploy-once && npm run build && npm run semantic-release
    fi
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
